FROM python:3.10-slim

# Crear directorio de trabajo
WORKDIR /app

# Copiar requerimientos y código
COPY requirements.txt ./requirements.txt
COPY . /app

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer puerto para la API
EXPOSE 8001

# Comando para ejecutar la API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
